### ISSUE TITLE
etcd有三个地址，那micro  api起在哪个地址上呢，这一点不是很懂

### ISSUE THREAD

**Issue by via123** [lpxxn/gomicrorpc#10]
etcdv3的集群，假如地址是a,b,c,那么micro  api 应该起在哪个地址上啊，假如起在a服务器上，a挂掉的话，api也会不能用了鸭，不太懂，能解答一下吗

**Comment by lpxxn** [comment]
etcdv3的是用做注册中心的，里面保存的是你的服务注册的地址信息，只要还有一个 etcdv3的节点在，服务端就能注册，客户端就能获取服务端的信息。
你 micro api 和这些节点的机器 没有关系，你在同了个网络下随便一台能访问到的机器上启动就行。
