### ISSUE TITLE
你好，运行example2时，我手动替换了etcdv3为consul，客户端运行到单向stream测试是出现了问题，从表现上看是客户端只Recv()了一次，在第二次Recv()的时候阻塞了。

### ISSUE THREAD

**Issue by hexxv** [lpxxn/gomicrorpc#12]
以下为控制台输出：
Cli：
msg:"hello world" values:"a" values:"b" header:<key:"name" value:<key:1 values:"abc" > > type:DESCEND
test stream get idx 1  data  value:"TQir" value:"NfvXafmU" value:"OyMOF" value:"EloEcZEaO" value:"PfIzI" value:"DWbKk" value:"VfSXx"

Srv:
2019/08/28 17:04:02 Transport [http] Listening on [::]:54023
2019/08/28 17:04:02 Broker [http] Connected to [::]:54024
2019/08/28 17:04:02 Registry [consul] Registering node: lp.srv.exg2-87ee00e1-7e71-4c2a-a8cb-7c2fa914f2d0
2019/08/28 17:04:02 Subscribing lp.srv.exg2-87ee00e1-7e71-4c2a-a8cb-7c2fa914f2d0 to topic: lp.srv.eg2.topic1
received hello server
Received message: Ixe

调试后发现 srv 已经Send了所有消息，而cli一直阻塞在第二次Recv.

代码改动上仅替换了EtcdV3 为 Consul，因为我还没搭etcd

consul是可以正常运行的

SayHello（）可以正常请求并返回

程序阻塞在了 GetStreamValues（）

目前不知道哪里有问题，望解答。

**Comment by lpxxn** [comment]
我跑了一下代码，确实是卡住了，原因是源码的变动导致的

https://github.com/micro/go-micro/blob/a4f5772555f017fdfde44c5a352c5ae42eb207eb/client/rpc_client.go#L215
```
c, err := r.pool.Get(address, dOpts...) 
```
从缓存里得到的连接信息，这的改动 造成的这个bug，因为得到的connection的`Stream`可能是` false`，

我已经提交了一个merge来修改这个问题
https://github.com/micro/go-micro/pull/705

如果你急用，可以用版本[v1.8.3](https://github.com/micro/go-micro/tree/v1.8.3)这个版本是没有修改stream方法的

**Comment by hexxv** [comment]
感谢解答^_^
