### ISSUE TITLE
默认的服务发现不是consul吧?

### ISSUE THREAD

**Issue by leo-je** [lpxxn/gomicrorpc#3]
安装consul之后,不启动,也能正常调用,查了一下官方说明,好像是mdns,是版本变化吗

**Comment by lpxxn** [comment]
版本有变化现在是 mdns 之前是consul 是默认的服务发现方式
今年刚换的。
![image](https://user-images.githubusercontent.com/7147958/57977289-dbb69500-7a27-11e9-8cc3-5c71f5b9e37f.png)


相关代码
https://github.com/micro/go-micro/blob/dc5ec0cdb292334d5a703c2e8ce08a533e384e58/registry/registry.go#L29
```
DefaultRegistry = NewRegistry()
```
https://github.com/micro/go-micro/blob/dc5ec0cdb292334d5a703c2e8ce08a533e384e58/registry/mdns_registry.go#L342
```
// NewRegistry returns a new default registry which is mdns
func NewRegistry(opts ...Option) Registry {
	return newRegistry(opts...)
}
```

**Comment by leo-je** [comment]
![image](https://user-images.githubusercontent.com/29834148/57838947-41bcd580-77f8-11e9-95cb-e34dd481e486.png)
我在<<go微服务框架go-micro深度学习(二) 入门例子>>中看到这个,所以有点疑惑
" go-micro服务发现默认使用的是consul"

**Comment by lpxxn** [comment]
找时间，我重新把 go-micro的git history 看了一下。我写帖子的时候确实是consul是默认的方式。今年改成的mdns
![image](https://user-images.githubusercontent.com/7147958/57977296-191b2280-7a28-11e9-97aa-09278ed7e651.png)

**Comment by lpxxn** [comment]
版本确实有变化了，我写帖子的时候是18年9月份，这个变动是19年修改的。

**Comment by lpxxn** [comment]
报歉，之前没过脑子就回答了问题。
