### ISSUE TITLE
example2 中执行到 stream报错

### ISSUE THREAD

**Issue by huangwei2013** [lpxxn/gomicrorpc#4]
example2 中执行到 stream时总报错

`
msg:"hello world" values:"a" values:"b" header:<key:"name" value:<key:1 values:"abc" > > type:DESCEND 
test stream get idx 1  data  value:"bnMVrek" value:"OcIipke" value:"IpNrdsG" value:"iBKy" value:"TSYEER" value:"WFCACpnn" value:"olvoyIP" 
test stream get idx 2  data  value:"aEvAl" value:"ueX" value:"rSxvUDFpV" value:"fAPNnn" value:"GinQ" value:"jgbsrHuGi" value:"vJawJ" 
test stream get idx 3  data  value:"uLMdJjKi" value:"RAxzum" value:"JqcjnMfqTR" value:"NfQi" value:"XEninrPhHf" value:"ySxcfEPqV" value:"WKWFiLIk" 
test stream get idx 4  data  value:"vOcJMqbT" value:"Uoagti" value:"smMABH" value:"tQMldlv" value:"Cvilnk" value:"SmtoNK" value:"nMuQfzGAT" 
test stream get idx 5  data  value:"QST" value:"TIS" value:"tiHgwD" value:"Vftrsf" value:"etozgX" value:"hRDjtT" value:"kQYfHW" 
test stream get idx 6  data  value:"KiDxDP" value:"AqgzHiZM" value:"gysMeM" value:"qVFaPDw" value:"muZRRTVY" value:"Aod" value:"SeCwUePSzN" 
test stream get idx 7  data  value:"jPGaUA" value:"GNMXmbCyO" value:"THJxJygj" value:"nvXZIi" value:"ZhMNey" value:"FTeHxJTpps" 
test stream get idx 8  data  value:"QtoEIOsT" value:"Baczsc" value:"BIP" value:"anSdHzqSRZ" value:"rCXTRIYQJ" value:"uPGvF" value:"NKRvi" 
test stream get idx 9  data  value:"nzqBx" value:"EMBQcJYIXf" value:"tfx" value:"SVjB" value:"rxf" value:"WVyfV" 
test stream get idx 10  data  value:"KnTHJEpmgC" value:"UjYxTfvH" value:"DrGk" value:"tJgPbdYTY" value:"vXNJTtFTV" value:"sxiSDt" value:"TWKjIKO" 
panic: {"id":"go.micro.client.transport","code":500,"detail":"unexpected EOF","status":"Internal Server Error"}

goroutine 1 [running]:
main.GetStreamValues(0xc6ac80, 0xc00000f300)
        /data/code/gopath/src/github.com/lpxxn/gomicrorpc/example2/cli/main.go:63 +0x352
main.main()
        /data/code/gopath/src/github.com/lpxxn/gomicrorpc/example2/cli/main.go:30 +0x1c1
exit status 2
`

**Comment by lpxxn** [comment]
我排查了一下，这个是因为go-micro源码变动导致的一个bug，这需要go-micro修改一下这个问题。我已经给go-micro的源码提交了解决方案，等源码更新，或者，你先暂时在你的代码里处理一下这个问题。
[我提交的修复这个bug的代码 ](https://github.com/micro/go-micro/pull/487)

**Comment by lpxxn** [comment]
go-micro已经把我提交的代码合并了，你获取一下最新的代码就能跑了。

**Comment by huangwei2013** [comment]
thx

但这个bug一直没被触发过吗。。。有点神奇 ：P

**Comment by lpxxn** [comment]
这个bug是前不久源码变动产生的，没多少天呢。
