### ISSUE TITLE
example1 例子运行报错

### ISSUE THREAD

**Issue by maiguangyang** [lpxxn/gomicrorpc#5]
[root@saas example1]# go run ./srv/main.go                                      
2019/05/26 12:17:14 Transport [http] Listening on [::]:15538
2019/05/26 12:17:14 Broker [http] Connected to [::]:26588
2019/05/26 12:17:14 Registry [etcdv3] Registering node: lp.srv.eg1-b061f606-6a18-4c51-b00d-3dcd329f8e94
2019/05/26 12:17:19 Server %s-%s register error: %slp.srv.eg1b061f606-6a18-4c51-b00d-3dcd329f8e94context deadline exceeded

------------------------------------------------------------------------------------------------

	// 我这里用的etcd 做为服务发现，如果使用consul可以去掉
	reg := etcdv3.NewRegistry(func(op *registry.Options){
		op.Addrs = []string{
			"127.0.0.1:2379",
		}
	})
------------------------------------------------------------------------------------------------
请问该如何解决？

**Comment by lpxxn** [comment]
你的etcd服务可能有问题，访问超时
```
2019/05/26 12:17:19 Server %s-%s register error: %slp.srv.eg1b061f606-6a18-4c51-b00d-3dcd329f8e94context deadline exceeded
```

**Comment by maiguangyang** [comment]
> 你的ETCD服务可能有问题，访问超时
> 
> ```
> 2019/05/26 12:17:19 Server %s-%s register error: %slp.srv.eg1b061f606-6a18-4c51-b00d-3dcd329f8e94context deadline exceeded
> ```

能指点一下，怎么去排查吗？现在完全不知道怎么操作了。
如果把etcd注释掉，启用consul作为服务发现，就一切正常。

**Comment by lpxxn** [comment]
* 首先你要先熟悉一下etcd的操作方法，看一下文档，如何进行远程操作。
* 你在你go服务器上访问一下你的etcd服务能不能访问，手动增删改一下数据。如果能操作就说明etcd服务没有问题。
* 如果手动操作没有问题，那就要看一下代码了，debug跟踪一下代码，看一下哪报的错，根据错误信息查看是具体是哪出的问题。

**Comment by maiguangyang** [comment]
> * 首先你人先熟悉一下etcd的操作方法，看一下文档，如何进行远程操作。
> * 你在你go服务器上访问一下你的etcd服务能不能访问，手动增删改一下数据。如果能操作就说明etcd服务没有问题。
> * 如果手动操作没有问题，那就要看一下代码了，debug跟踪一下代码，看一下哪报的错，根据错误信息查看是具体是哪出的问题。

好的，谢谢了
