### ISSUE TITLE
客户端和服务端的双向流问题

### ISSUE THREAD

**Issue by jayn1985** [lpxxn/gomicrorpc#7]
我用你的样例2的代码在本地跑了一下，客户端到服务端的单向Stream是可以正常运行的，但是双向Stream的例子一直失败，直观的表现就是客户端的代码被阻塞了（客户端主goroutine的Recv方法和另起的goroutine中的Send方法），没有任何输出产生，想请教下这个会是什么原因导致的，谢谢

**Comment by lpxxn** [comment]
源码里Rev和send加上锁了，已经和go-micro的作者交流过了。在修改中，我也修改了我的例子，可以跑了。
